### ISSUE TITLE
Typo in fileset.php

### ISSUE THREAD

**Issue by ConcreteOwl** [JeRoNZ/concrete5_fileset_migration#1]
On line 46 of the application/contollers/fileset.php file we have this:
`$json = json_decode(file_get_contents('filesets.json'), true);`
This causes an error because the json file is named fileset.json and not filesets.json
Fixing the typo allows the file to run successfully.
Thanks for this very handy utility.

**Comment by JeRoNZ** [comment]
Glad you found it useful. I must admit that I generally used this with wget ... -O filesets.json so it was never an issue. However, I've added a content disposition header with the filename set to filesets.json which ought to resolve it.
